language: php
sudo: false
php:
- 5.6
- 7.0
- 7.1
- 7.2
before_install: composer install
script: vendor/bin/phpunit
env:
  secure: RO7Agz8O5bYMhfZul7rHuAZTJRmi4YcCF95zL/HYCXxcuua1bnpvi5X2D+0qWt1wTxaYYqAH+Da2au3pa/SqRc9PBJG8XJQ6U43MZIbCcAEXN4M7J0G65WzJsTBSgRJIV/JqX/f/CNOHmMm4ZDtV32heEhjwW2R87eIZEtJ5x3yAyjl3qzremUcfkUQ4W2y22v0qzGBU6n/dVDMfZ4usU6dRR/wDLlOMPXwSXazT8EmeDVCBwqosIfu7FbWXcS36/suNCSdBV78zgr6bMoZsxYVo/L/eo4MXhjfbkh+f86Kg77OzUh9ha7KPnaU81hFCsSiwRzQUxifw66ZiES97POZOCCvMr31ouKYUwFQvn7AKihDibk8ZUhsuexRdpXJaxsU7m5aL+YH5FUtRhOtIHOu3jChY2q6l2SVcbEIQicWUGKNwl+Ox29vF+Dcxr6sl+Pfvby1ecygM/USf3W2TNMOlMDCOVac4DlQnRYPZeXKVSSDiAQQkw03NCCpTxteqT2fcepp4amOlbTm1AShmwH/ZTxcN5WfDw15ugbEMxlDYKuJm+s+xab+pTwQ6MYhCW2JlxnksuVnRyfX2lHTbYPO/xk92+T6FaBK73DUK/b5nAXmCzCeg03sXkmL/KjAAOY6vMG5h0mV+sZVsgzTQ6W5dm3HfBQU0NG8PROkvoh0=
