<?php
/**
 * ServerApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Upcloud api
 *
 * The UpCloud API consists of operations used to control resources on UpCloud. The API is a web service interface. HTTPS is used to connect to the API. The API follows the principles of a RESTful web service wherever possible. The base URL for all API operations is  https://api.upcloud.com/. All API operations require authentication.
 *
 * OpenAPI spec version: 1.2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * ServerApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ServerApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for assignTag
     *
     * Assign tag to a server.
     *
     */
    public function testAssignTag()
    {
    }

    /**
     * Test case for attachStorage
     *
     * Attach storage.
     *
     */
    public function testAttachStorage()
    {
    }

    /**
     * Test case for createFirewallRule
     *
     * Create firewall rule.
     *
     */
    public function testCreateFirewallRule()
    {
    }

    /**
     * Test case for createServer
     *
     * Create server.
     *
     */
    public function testCreateServer()
    {
    }

    /**
     * Test case for deleteFirewallRule
     *
     * Remove firewall rule.
     *
     */
    public function testDeleteFirewallRule()
    {
    }

    /**
     * Test case for deleteServer
     *
     * Delete server.
     *
     */
    public function testDeleteServer()
    {
    }

    /**
     * Test case for detachStorage
     *
     * Detach storage.
     *
     */
    public function testDetachStorage()
    {
    }

    /**
     * Test case for ejectCdrom
     *
     * Eject CD-ROM.
     *
     */
    public function testEjectCdrom()
    {
    }

    /**
     * Test case for getFirewallRule
     *
     * Get firewall rule details.
     *
     */
    public function testGetFirewallRule()
    {
    }

    /**
     * Test case for listServerConfigurations
     *
     * List server configurations.
     *
     */
    public function testListServerConfigurations()
    {
    }

    /**
     * Test case for listServers
     *
     * List of servers.
     *
     */
    public function testListServers()
    {
    }

    /**
     * Test case for loadCdrom
     *
     * Load CD-ROM.
     *
     */
    public function testLoadCdrom()
    {
    }

    /**
     * Test case for modifyServer
     *
     * Modify server.
     *
     */
    public function testModifyServer()
    {
    }

    /**
     * Test case for restartServer
     *
     * Restart server.
     *
     */
    public function testRestartServer()
    {
    }

    /**
     * Test case for serverDetails
     *
     * Get server details.
     *
     */
    public function testServerDetails()
    {
    }

    /**
     * Test case for serverServerIdFirewallRuleGet
     *
     * List firewall rules.
     *
     */
    public function testServerServerIdFirewallRuleGet()
    {
    }

    /**
     * Test case for startServer
     *
     * Start server.
     *
     */
    public function testStartServer()
    {
    }

    /**
     * Test case for stopServer
     *
     * Stop server.
     *
     */
    public function testStopServer()
    {
    }

    /**
     * Test case for untag
     *
     * Remove tag from server.
     *
     */
    public function testUntag()
    {
    }
}
