<?php
/**
 * ServerApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Upcloud api
 *
 * Upcloud api specification
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * ServerApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ServerApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for serverGet
     *
     * List of servers.
     *
     */
    public function testServerGet()
    {
    }

    /**
     * Test case for serverPost
     *
     * Create server.
     *
     */
    public function testServerPost()
    {
    }

    /**
     * Test case for serverServerIdDelete
     *
     * Delete server.
     *
     */
    public function testServerServerIdDelete()
    {
    }

    /**
     * Test case for serverServerIdGet
     *
     * Server details.
     *
     */
    public function testServerServerIdGet()
    {
    }

    /**
     * Test case for serverServerIdPut
     *
     * Modify server.
     *
     */
    public function testServerServerIdPut()
    {
    }
}
