<?php
/**
 * TagApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Upcloud api
 *
 * The UpCloud API consists of operations used to control resources on UpCloud. The API is a web service interface. HTTPS is used to connect to the API. The API follows the principles of a RESTful web service wherever possible. The base URL for all API operations is  https://api.upcloud.com/. All API operations require authentication.
 *
 * OpenAPI spec version: 1.2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * TagApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class TagApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for assignTag
     *
     * Assign tag to a server.
     *
     */
    public function testAssignTag()
    {
    }

    /**
     * Test case for createTag
     *
     * Create a new tag.
     *
     */
    public function testCreateTag()
    {
    }

    /**
     * Test case for deleteTag
     *
     * Delete tag.
     *
     */
    public function testDeleteTag()
    {
    }

    /**
     * Test case for listTags
     *
     * List existing tags.
     *
     */
    public function testListTags()
    {
    }

    /**
     * Test case for modifyTag
     *
     * Modify existing tag.
     *
     */
    public function testModifyTag()
    {
    }

    /**
     * Test case for untag
     *
     * Remove tag from server.
     *
     */
    public function testUntag()
    {
    }
}
