<?php
/**
 * ServerTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Upcloud api
 *
 * Upcloud api specification
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ServerTest Class Doc Comment
 *
 * @category    Class */
// * @description Server
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ServerTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Server"
     */
    public function testServer()
    {
    }

    /**
     * Test attribute "boot_order"
     */
    public function testPropertyBootOrder()
    {
    }

    /**
     * Test attribute "core_number"
     */
    public function testPropertyCoreNumber()
    {
    }

    /**
     * Test attribute "firewall"
     */
    public function testPropertyFirewall()
    {
    }

    /**
     * Test attribute "host"
     */
    public function testPropertyHost()
    {
    }

    /**
     * Test attribute "hostname"
     */
    public function testPropertyHostname()
    {
    }

    /**
     * Test attribute "ip_addresses"
     */
    public function testPropertyIpAddresses()
    {
    }

    /**
     * Test attribute "license"
     */
    public function testPropertyLicense()
    {
    }

    /**
     * Test attribute "memory_amount"
     */
    public function testPropertyMemoryAmount()
    {
    }

    /**
     * Test attribute "nic_model"
     */
    public function testPropertyNicModel()
    {
    }

    /**
     * Test attribute "plan"
     */
    public function testPropertyPlan()
    {
    }

    /**
     * Test attribute "plan_ipv4_bytes"
     */
    public function testPropertyPlanIpv4Bytes()
    {
    }

    /**
     * Test attribute "plan_ipv6_bytes"
     */
    public function testPropertyPlanIpv6Bytes()
    {
    }

    /**
     * Test attribute "state"
     */
    public function testPropertyState()
    {
    }

    /**
     * Test attribute "storage_devices"
     */
    public function testPropertyStorageDevices()
    {
    }

    /**
     * Test attribute "tags"
     */
    public function testPropertyTags()
    {
    }

    /**
     * Test attribute "timezone"
     */
    public function testPropertyTimezone()
    {
    }

    /**
     * Test attribute "title"
     */
    public function testPropertyTitle()
    {
    }

    /**
     * Test attribute "uuid"
     */
    public function testPropertyUuid()
    {
    }

    /**
     * Test attribute "video_model"
     */
    public function testPropertyVideoModel()
    {
    }

    /**
     * Test attribute "vnc"
     */
    public function testPropertyVnc()
    {
    }

    /**
     * Test attribute "vnc_host"
     */
    public function testPropertyVncHost()
    {
    }

    /**
     * Test attribute "vnc_password"
     */
    public function testPropertyVncPassword()
    {
    }

    /**
     * Test attribute "vnc_port"
     */
    public function testPropertyVncPort()
    {
    }

    /**
     * Test attribute "zone"
     */
    public function testPropertyZone()
    {
    }
}
